name: Visitreports API
on:
  push:
    branches: [features/github-actions]
    paths:
      - .github/workflows/visitreports.yaml
      - day4/apps/nodejs/visitreport/*
      - day4/apps/infrastructure/templates/scm-visitreport-nodejs-db.json
      - day4/apps/infrastructure/templates/scm-visitreport-nodejs-infra.json

env:
  RESOURCE_GROUP_NAME: SCM-GITHUB-ACTION-COMMON-RG
  APPLICATION_INSIGHTS_NAME: scm-contacts-insights
  SERVICE_BUS_NAMESPACE: scm-shared-service-bus
  RESOURCES_APP_NAME: scm-visitreport-api-github
  COSMOS_DB_ACCOUNT_NAME: scm-contacts-cosmos-db
  COSMOS_DATABASE_NAME: scmvisitreports
  COSMOS_DATABASE_CONTAINER_NAME: visitreports

jobs:
  extract-arm-templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload the ARM Template as build artifact
        uses: actions/upload-artifact@v2
        with:
          name: db-template
          path: day4/apps/infrastructure/templates/scm-visitreport-nodejs-db.json
          if-no-files-found: error
          retention-days: 90
      - name: Upload the ARM Template as build artifact
        uses: actions/upload-artifact@v2
        with:
          name: infra-template
          path: day4/apps/infrastructure/templates/scm-visitreport-nodejs-infra.json
          if-no-files-found: error
          retention-days: 90

  deploy-db-template:
    runs-on: ubuntu-latest
    needs: extract-arm-templates
    steps:
      - name: Download the arm template
        uses: actions/download-artifact@v2
        with:
          name: db-template
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: scm-visitreport-nodejs-db.json
          deploymentMode: Incremental
          parameters: >
            cosmosDbAccount=${{ env.COSMOS_DB_ACCOUNT_NAME }}
            cosmosDatabaseName=${{ env.COSMOS_DATABASE_NAME }}
            cosmosDatabaseContainerName=${{ env.COSMOS_DATABASE_CONTAINER_NAME }}

  deploy-infra-template:
    runs-on: ubuntu-latest
    needs: extract-arm-templates
    steps:
      - name: Download the arm template
        uses: actions/download-artifact@v2
        with:
          name: infra-template
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: scm-visitreport-nodejs-infra.json
          deploymentMode: Incremental
          parameters: >
            cosmosDbAccount=${{ env.COSMOS_DB_ACCOUNT_NAME }}
            webAppName=${{ env.RESOURCES_APP_NAME }} 
            applicationInsightsName=${{ env.APPLICATION_INSIGHTS_NAME }}
            serviceBusNamespaceName=${{ env.SERVICE_BUS_NAMESPACE }}
            commonResGroup=${{ env.RESOURCE_GROUP_NAME }}

  build-and-deploy-api:
    runs-on: ubuntu-latest
    needs:
      - deploy-db-template
      - deploy-infra-template
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache npm dependencies to speed up deployment
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('day4/apps/nodejs/visitreport/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: npm install, build, and test
        working-directory: day4/apps/nodejs/visitreport
        run: | # The following lines are joined by a newline (\n) character
          npm install
          npm run build --if-present
          npm run test --if-present
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.RESOURCES_APP_NAME }}
          package: day4/apps/nodejs/visitreport
